name: GitHub Actions Demo

on: [push]

jobs:
  gitHubActionsDemo:
    runs-on: ubuntu-latest

    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      # Étape 2 : Configuration de l'agent SSH
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Étape 3 : Ajouter le serveur distant aux known_hosts
      - name: Add remote server to known_hosts
        run: ssh-keyscan -H 151.80.58.182 >> ~/.ssh/known_hosts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript
        run: npx tsc --noEmit

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run ESLint
        run: npx eslint .

      - name: Build project
        run: npm run build

      - name: Message de fin
        run: echo "🎉 Tout est Ok !"
